foreground              #FFFFFF
background              #181214
selection_foreground    #181214
selection_background    #FFFFFF
cursor                  #C5CDD0
cursor_text_color       #080808

active_tab_foreground     #181214
active_tab_background     #8D979B
inactive_tab_foreground   #8D979B
inactive_tab_background   #181214

# black
color0      #522936
color8      #8F576A

# red
color1      #CCF1FF
color9      #AADDF0

# green
color2      #FFD5CC
color10     #F0B7AA

# yellow
color3      #CCF0FF
color11     #AADCF0

# blue
color4      #E69AB3
color12     #E69AB3

# magenta
color5      #E6A79A
color13     #E6A79A

# cyan
color6      #9AD0E6
color14     #9AD0E6

# white
color7      #CCF1FF
color15     #AADDF0
