
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

# See https://wiki.hypr.land/Configuring/Monitors/
# Using description-based matching for stability across reboots

# Samsung (DP-1)
monitor = desc:Samsung Electric Company LC27G7xT HNBW800080, 2560x1440@240, 0x0, 1
# MSI Optix (DP-2)
monitor = desc:Microstep Optix G24C 0x00000001, 1920x1080@120, 2560x0, 1

# Fallback
monitor = , preferred, auto, 1
